filegroup(
    name = "traces",
    srcs = [
        "onoro.trace",
        "onoro-cc.trace",
        "simple.trace",
        "simple_calloc.trace",
        "simple_realloc.trace",
    ],
    visibility = ["//visibility:public"],
)
