
cc_library(
    name = "math",
    hdrs = ["math.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "assert",
    hdrs = ["assert.h"],
    deps = [
        "@abseil-cpp//absl/strings",
    ],
    visibility = ["//visibility:public"],
)
